# midi/playback.py
import threading

class PlaybackEngine:
    """Handles scheduled playback of notes generated by the Parasite Swarm"""
    def __init__(self, midi_io):
        self.midi_io = midi_io

    def schedule_note(self, note, velocity, duration_sec, delay_sec=0.0):
        # Clamp note to valid MIDI range (0-127)
        safe_note = max(0, min(127, int(note)))
        safe_velocity = max(0, min(127, int(velocity)))

        def _play_task():
            self.midi_io.send_note_on(safe_note, safe_velocity)
            # Schedule the note off
            threading.Timer(duration_sec, self.midi_io.send_note_off, args=[safe_note]).start()

        if delay_sec > 0:
            threading.Timer(delay_sec, _play_task).start()
        else:
            _play_task()