# midi/playback.py
import threading

class PlaybackEngine:
    """Handles scheduled playback of notes generated by the Parasite Swarm."""
    def __init__(self, midi_io):
        self.midi_io = midi_io
        self._timers = []
        self._lock = threading.Lock()

    def schedule_note(self, note, velocity, duration_sec, delay_sec=0.0):
        # Clamp note to valid MIDI range (0-127)
        safe_note = max(0, min(127, int(note)))
        safe_velocity = max(0, min(127, int(velocity)))

        def _play_task():
            self.midi_io.send_note_on(safe_note, safe_velocity)
            off_timer = threading.Timer(duration_sec, self.midi_io.send_note_off, args=[safe_note])
            off_timer.daemon = True
            self._track(off_timer)
            off_timer.start()

        if delay_sec > 0:
            t = threading.Timer(delay_sec, _play_task)
            t.daemon = True
            self._track(t)
            t.start()
        else:
            _play_task()

    def cancel_all(self):
        """Cancel all pending timers — silences the swarm immediately."""
        with self._lock:
            for t in self._timers:
                t.cancel()
            self._timers.clear()

    def _track(self, timer):
        with self._lock:
            # Prune completed timers to avoid unbounded growth
            self._timers = [t for t in self._timers if t.is_alive()]
            self._timers.append(timer)
